### ISSUE TITLE
Is there any log?

### ISSUE THREAD

**Issue by danielo515** [b0o/SchemaStore.nvim#12]
Hello! Thanks for this wonderful and helpful tool.
I just added a new json schema to my configuration, but it is not being picked up. I was wondering if there is any log I can check to understand why may be happening?

In any case, here is my config

```lua
  lspManager.setup("jsonls", {
    settings = {
      json = {
        schemas = vim.list_extend({
          {
            description = "Haxe format schema",
            fileMatch = { "hxformat.json" },
            name = "hxformat.schema.json",
            url = "https://raw.githubusercontent.com/vshaxe/vshaxe/master/schemas/hxformat.schema.json",
          },
        }, require("schemastore").json.schemas()),
        validate = { enable = true },
      },
    },
  })
```

**Comment by b0o** [comment]
You can try looking through the LSP logs: `:lua vim.cmd("edit " .. vim.lsp.get_log_path())`

This may also help: https://www.reddit.com/r/neovim/comments/sbohdv/help_installing_jsonls_schemas

**Comment by danielo515** [comment]
I'm using the same configuration in another neovim config file and it just works as expected. It is probably an issue with LunarVim.
Thanks for your help.
