### ISSUE TITLE
Can this be used with .js form of .json files?

### ISSUE THREAD

**Issue by kutsan** [b0o/SchemaStore.nvim#2]
Like `.eslintrc.js`, `prettier.config.js`, `.prettier.js`, `babel.config.js`, `.babelrc.js` and such. JSON ones work perfectly for me but some of the files I used is in their `.js` form. Is there a workaround for them?

Great plugin by the way, thanks!

**Comment by b0o** [comment]
Great question. I agree that this would be a nice feature. Unfortunately, at the moment I do not think this is possible with any JSON schema consumer. Additionally, the SchemaStore catalog doesn’t contain patterns to match against the JS versions of these files.

This may be a good question for the upstream SchemaStore project as well as the JavaScript language server you use.

**Comment by b0o** [comment]
I'm going to close this, let me know if you have any other questions.
