### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by zyriab** [b0o/SchemaStore.nvim#25]
Any chance to get TOML support?
According to the [TOML docs](https://taplo.tamasfe.dev/configuration/directives.html#the-schema-directive), it supports JSON schema.

I'd be happy to help :)

**Comment by b0o** [comment]
I'm open to this, but the taplo docs don't specify if it supports a similar configuration strategy to jsonls/yamlls. In both of those LSPs, you can pass a list of JSON schemas in the [LSP configuration](https://github.com/neovim/nvim-lspconfig/blob/d1bab4cf4b69e49d6058028fd933d8ef5e74e680/doc/lspconfig.txt#L175-L199). Reading through the taplo docs, I can't find anything about this.

If you look into this further and report back how we can pass the list of schemas to taplo, I'm happy to help add support to SchemaStore.nvim.

**Comment by zyriab** [comment]
Hey @b0o, thanks for the quick answer!
I'll look into it :)
I've found [this](https://docs.rs/taplo-lsp/0.7.0/taplo_lsp/config/struct.LspConfig.html#structfield.schema) in the `taplo-lsp` rust docs but I'm not sure I'm looking at the right place.

Have a good one!

**Comment by zyriab** [comment]
Apparently taplo uses the SchemaStore catalog by default, sorry for wasting your time :D
