### ISSUE TITLE
Scheme is missing for bitbucket-pipelines.yml

### ISSUE THREAD

**Issue by afranioce** [b0o/SchemaStore.nvim#27]
When I try to open the file `bitbucket-pipelines.yml` throw error below

```
Error executing vim.schedule lua callback: ...l/Cellar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp.lua:1308: RPC[Error] code_name = InternalError, message = "Request initialize failed with me
ssage: [UriError]: Scheme is missing: {scheme: \"\", authority: \"\", path: \"null\", query: \"\", fragment: \"\"}"
stack traceback:
        [C]: in function 'assert'
        ...l/Cellar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp.lua:1308: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I have tested the other yaml like `docker-compose.yml` and works well

**Comment by afranioce** [comment]
There is a official scheme file for bitbucket pipeline as commented in this post https://community.atlassian.com/t5/Bitbucket-questions/Scheme-URL-of-bitbucket-pipelines-yml/qaq-p/834807 

The scheme link is https://api.bitbucket.org/schemas/pipelines-configuration

**Comment by b0o** [comment]
Please see #40
