### ISSUE TITLE
FHIR schema

### ISSUE THREAD

**Issue by realtica** [b0o/SchemaStore.nvim#29]
Hello, could you add [FHIR R4 schema](https://hl7.org/fhir/R4/fhir.schema.json.zip) to the repo?

I've tried to add it locally, but it doesn't work :(

```
require("schemastore").json.schemas({
  extra = {
    {
      description = "FHIR JSON schema",
      fileMatch = "*.fhir.json",
      name = "fhir.json",
      url = "/home/me/fhir.schema.json",       -- or '/path/to/your/schema.json'
    },
  },
})
```
Also, I've moved to "extra" to jsonls config, and nothing happens..

**Comment by b0o** [comment]
> Hello, could you add FHIR R4 schema to the repo?

We don't manage the catalog, we pull from the main SchemaStore repo. Please open an issue upstream: https://github.com/SchemaStore/schemastore/issues

> I've tried to add it locally, but it doesn't work

It worked for me: 

![2024-04-03_13-29-33_region](https://github.com/b0o/SchemaStore.nvim/assets/21299126/8fbb84ee-5b9e-410c-b890-1d63add86e4e)

Are you sure that your file has a matching extension? Try doing `:lua vim.lsp.buf.hover()` while your cursor is over a field in the json file, it should show documentation.
