### ISSUE TITLE
Extend for yaml / yml

### ISSUE THREAD

**Issue by lucax88x** [b0o/SchemaStore.nvim#3]
Hi!

can we extend the plugin for yml files?

this is an example:

https://github.com/neovim/nvim-lspconfig/issues/229

**Comment by b0o** [comment]
Hello! `yamlls` already has [built-in SchemaStore support](https://github.com/redhat-developer/yaml-language-server#language-server-settings):

> `yaml.schemaStore.enable`: When set to true the YAML language server will pull in all available schemas from JSON Schema Store

Alternatively, if you still want to use this plugin, I have seen instances of people using it with `yamlls`. [Here’s an example](https://github.com/yriveiro/nvim-files/blob/153bcfbe26d4c52fabe693d76f2d5274696ba0f0/lua/lsp/yaml.lua) I found by searching GitHub. I haven’t tested this myself, though.

**Comment by lucax88x** [comment]
Thanks!
