### ISSUE TITLE
Behavior: More specific file matchers should override less specific ones

### ISSUE THREAD

**Issue by xav-ie** [b0o/SchemaStore.nvim#31]
I was surprised to find that my tsconfig.settings.json was using the Micro JSON schema. I think that more specific FileMatchers should take precedence over less specific ones. Here is where I ran into the issue:
https://github.com/b0o/SchemaStore.nvim/pull/30

**Comment by b0o** [comment]
Hi @xav-ie, is your original issue resolved now that https://github.com/SchemaStore/schemastore/pull/3717 is merged?

**Comment by xav-ie** [comment]
Yes, this looks good now. Thank you!
