### ISSUE TITLE
.stylelintrc not picked up unless explicitly added $schema 

### ISSUE THREAD

**Issue by bezlant** [b0o/SchemaStore.nvim#38]
It doesn't work in my .stylelintrc if $schema not added explicitly. Using latest neovim on macos.

<img width="460" alt="Screenshot 2024-08-01 at 3 57 30 PM" src="https://github.com/user-attachments/assets/08b19e23-6006-4372-b4a0-3f52170b6b3c">

<img width="506" alt="Screenshot 2024-08-01 at 3 57 24 PM" src="https://github.com/user-attachments/assets/a6d50cef-54d6-4411-8809-768cadbe8209">

**Comment by b0o** [comment]
Hi there. Can you share the config you're using? Also, does SchemaStore.nvim work for any other kinds of files?

**Comment by bezlant** [comment]
Yes, it does work in yaml, json files.
Here is my config https://github.com/bezlant/nvim/blob/ee1e40ae246c7248c9752a8a00b5315a1bd46d4d/lua/config/plugins.lua#L494

<img width="461" alt="Screenshot 2024-08-09 at 10 24 09 PM" src="https://github.com/user-attachments/assets/e3b93aa9-917b-4076-89a6-637244f05145">

**Comment by bezlant** [comment]
I've discovered it was my bad. I didn't realise I'm supposed to explicitly connect it to jsonls language server. I've done it now and works like a charm.
