### ISSUE TITLE
expand the fileMatch argument for GitLab CI configuration files

### ISSUE THREAD

**Issue by alsmnn** [b0o/SchemaStore.nvim#39]
Hey everyone and thanks for the great plugin!
To break the gitlab ci configuration into smaller files it is possible to put them into the folder `.gitlab/ci`. Then you can `include` these files in the `.gitlab-ci.yml` file, which is lying in the root dir of the project.
This makes it easy to work with complex pipelines.
In [catalog.lua](https://github.com/b0o/SchemaStore.nvim/blob/218a9887085b81b3eb0ee8f1e2d20c4a7fd7b1c9/lua/schemastore/catalog.lua#L2623) you could expand the `fileMatch` argument with the following parameters:
`".gitlab/ci/*.yml", ".gitlab/ci/*.yaml"` 
This would be great, so you could organize the files as the stages or jobs they represent.

**Comment by b0o** [comment]
Hi, thanks for the kind words. The `catalog.lua` file is auto-generated based on the upstream [SchemaStore](https://github.com/SchemaStore/schemastore) repo. I would recommend opening an issue or PR there. After the changes are merged upstream, this repo will re-generate the catalog automatically.
