### ISSUE TITLE
Support for tsconfig.*.json

### ISSUE THREAD

**Issue by Zangetsu101** [b0o/SchemaStore.nvim#5]
The tsconfig.json doesn't seem to match tsconfig.*.json files.
I tried adding this:
```
schemas = require('schemastore').json.schemas {
  select = {
    '.eslintrc',
    'lerna.json',
    'package.json',
    'prettierrc.json',
    'tsconfig.json',
    'tslint.json'
  },
  replace = {
    ['tsconfig.json'] = {
      description = 'Custom JSON schema for typescript configuration files',
      fileMatch = {'tsconfig*.json'},
      name = '.tsconfig.json',
      url = 'https://json.schemastore.org/tsconfig.json'
    }
  }
}
```
Any ideas?

**Comment by b0o** [comment]
Hey, thank you for the report! It led me to discover that I recently introduced a bug causing `select` and `replace` not to work together as expected. Can you try the latest version?

**Comment by b0o** [comment]
There is also is an issue with your example. You should keep the name `tsconfig.json` the same, not change it to `.tsconfig.json` in the `replace`, otherwise the `select` won't find it. This should work:

```lua
schemas = require('schemastore').json.schemas {
  select = {
    '.eslintrc',
    'lerna.json',
    'package.json',
    'prettierrc.json',
    'tsconfig.json',
    'tslint.json'
  },
  replace = {
    ['tsconfig.json'] = {
      description = 'Custom JSON schema for typescript configuration files',
      fileMatch = {'tsconfig*.json'},
      name = 'tsconfig.json',
      url = 'https://json.schemastore.org/tsconfig.json'
    }
  }
}
```

**Comment by Zangetsu101** [comment]
`.tsconfig.json` was my bad. Thanks for pointing that out.
And it is working as expected after updating to the latest version.
Anyway just wondering shouldn't the `fileMatch` be `tsconfig*.json` out of the box?

**Comment by b0o** [comment]
> And it is working as expected after updating to the latest version.

Awesome, glad it's working.

> Anyway just wondering shouldn't the fileMatch be tsconfig*.json out of the box?

You'll want to raise that issue [upstream](https://github.com/SchemaStore/schemastore), this repo is just consuming the catalog.
