### ISSUE TITLE
now.json seems to be deprecated

### ISSUE THREAD

**Issue by olrtg** [b0o/SchemaStore.nvim#6]
After the ZEIT rebrand to Vercel seems like the `now.json` file now should be named `vercel.json`. (see https://github.com/codesandbox/codesandbox-client/issues/5052).

I have also found the schema (hosted by Vercel): https://vercel.com/changelog/schema-autocomplete-and-validation-for-vercel-json.

I have tried to compare the two files but i couldn't tell if there are differences.

The docs for the `vercel.json` file: https://vercel.com/docs/cli#project-configuration

I'm willing to make a PR but i don't know if i should add `vercel.json` to the `fileMatch`, create a new schema and/or delete the older schema.

Any recommendations?

**Comment by b0o** [comment]
Hi! This project doesn't control the schema catalog, it just converts the catalog into a Neovim-friendly format. Please raise an issue [upstream](https://github.com/SchemaStore/schemastore) for issues related to adding/removing/changing schemas.

That being said, `vercel.json` is already supported: https://github.com/b0o/SchemaStore.nvim/blob/002444f8c9c69eaf1f755ef1bd91c0860ec56cb9/lua/schemastore/catalog.lua#L905-L910

Are you having trouble getting the Vercel schema working?

**Comment by olrtg** [comment]
Oh! my bad 😅  nevermind me then.
Now that you mencioned, for files that have the `*.json` extension works fine, but I'm having trouble with files like `.prettierrc` and `.eslintrc` (the lsp is attached correctly, which is jsonls in my case).. But idk, i'm pretty much new 
to nvim and I'm pretty sure that is just a misconfiguration on my side.

```lua
require('lspconfig').jsonls.setup {
  settings = {
    json = {
      schemas = require('schemastore').json.schemas(),
    },
  },
}
```

I'm using this setup. If you have any idea of what's possibly wrong you'll make my night haha.

**Comment by olrtg** [comment]
Hi! thanks the quick reply.
My bad then 😅  sorry about that.

**Comment by b0o** [comment]
No worries! Everything is working for you then? Happy to help if not.

**Comment by amin1419** [comment]
https://github.com/b0o/SchemaStore.nvim/issues/6#issue-1134653530
