### ISSUE TITLE
Using local schema repo

### ISSUE THREAD

**Issue by pedro757** [b0o/SchemaStore.nvim#7]
I'm contributing to the schemastore repo but I would like to see if my changes work before creating a PR. Is it possible to use a local schema?

**Comment by b0o** [comment]
This is a good idea, I'm open to a PR adding this feature.

**Comment by Ajibaji** [comment]
im using this to point to a local ado pipelines yaml schema:
`
schemas = vim.list_extend(
          {
            ['/path/to/custom-schemas/ado-pipelines.json'] = {
              'ado/**/*.y*ml',
              '**/*azure*.y*ml',
              '**/*ado*.y*ml',
              '**/*ipeline*/**/*.y*ml',
            }
          },
          require('schemastore').yaml.schemas()
        ),
`

**Comment by pixelprogrammer** [comment]
> This is a good idea, I'm open to a PR adding this feature.

Just confirming that this feature still doesn't exist correct?

**Comment by b0o** [comment]
@pixelprogrammer That's correct. 

@Ajibaji That's not quite the same thing as what this issue is requesting.

**Comment by Zachiah** [comment]
Hi. I'm looking to implement this. Is there a proposed API? I was thinking allowing `file://` urls in the `extra[].url` option. Would this work?

**Comment by b0o** [comment]
@Zachiah I actually just tested this with jsonls and it already works!

```lua
require('schemastore').json.schemas {
  replace = {
    ['package.json'] = {
      description = 'package.json overridden',
      fileMatch = { 'package.json' },
      name = 'package.json',
      url = 'file:///tmp/packagejson-schema.json',
    },
  },
}
```

I haven't tested yamlls.

**Comment by Zachiah** [comment]
Interesting haha. So to be clear, assuming yamlls works, there is no longer anything to do here?

**Comment by b0o** [comment]
I just tested yamlls and it works as well. Also, both jsonls and yamlls support raw paths like `/tmp/foo/bar.json` as well as file URIs like `file:///tmp/foo/bar.json`. I agree, we should update the docs to reflect this.

**Comment by Zachiah** [comment]
OK. Cool. Are you good with me making a PR to update the docs?

**Comment by b0o** [comment]
That would be great!
